### ISSUE TITLE
Loans Beckn Spec

### ISSUE THREAD

**Issue by karntrehan** [Konnect-Agri/AgriDex-Beckn#32]
We should start building a mortages spec for our protocol server. Beckn is already working on a spec which we will try to get hold of as well. 

- [ ] Get mortgages as a core spec
     - Beckn is working on a finance spec with ONDC.
     - They are difficult to get hold of and not available on discord. We are trying other routes to get this expedited.

- [ ] Add mortgages to our protocol server
    - Get mortgages added as a domain on the official beckn registry (registry.becknprotocol.io) and register our BPP under that domain. (Will need to get in touch with Venky and Beckn team for this)
    - In case the Beckn team disagrees with (ii), we can either fork and deploy their registry which is made by Venky in Java and using a backend framework he himself authored, or we can fine tune the registry created by Abhishek Pal (no docs or postman collection around that) and change the protocol server implementation to use that registry.

**Comment by karntrehan** [comment]
Work on mortgage spec - @charanpreet-samagra & @techsavvyash 

To be reviewed by @karntrehan @suresh12 @ChakshuGautam Rahul

**Comment by karntrehan** [comment]
https://github.com/beckn/protocol-specifications/discussions/363

@charanpreet-samagra & @techsavvyash to work on domain spec.

**Comment by karntrehan** [comment]
Ravi's comment reviewed. 
Thought process added to an MD file. We have a sheet of loan application form of all banks. Mapping each form element to each spec. 
X-Input & Tags to be used as much as possible. 

Loan details top level element to be explored. 

Clarify on the ticket that we are not looking for a core spec but an adaptation like dsep.

**Comment by karntrehan** [comment]
Blocked as @charanpreet-samagra is OOO for this week.

**Comment by techsavvyash** [comment]
Spec first draft finalised for `/select`, `/init`, `/confirm`. 

Need to start with `/search` and then get the spec reviewed from a finance field person.

**Comment by karntrehan** [comment]
Working doc: https://docs.google.com/document/d/1JrS20ERlCwD-XVzrfIQ4JtTJnk1zLvN1-Sw7b-NY3EI/edit

@aashutosh-samagra @karntrehan @suresh12 @ChakshuGautam to review.

**Comment by karntrehan** [comment]
Comment posted on the original discussion: https://github.com/beckn/protocol-specifications/discussions/363#discussioncomment-6508627

Update awaited from beckn team.
